package threads

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/nathanaday/claude-atlas/internal/project"
	"github.com/nathanaday/claude-atlas/internal/vault"
)

// cardFront renders a new card's frontmatter; Sync writes the body.
func cardFront(t Thread) string {
	return fmt.Sprintf("---\ntype: thread\nthread_id: %s\ntitle: %q\nstage: %s\noutcome: %q\npriority: %s\nphase: %q\nblocked: %q\ncreated: %s\nupdated: %s\n---\n",
		t.ID, t.Title, Stub, "", t.Priority, t.Phase, t.Blocked, t.Created, t.Updated)
}

// docPage renders a new stage document: frontmatter, the callout code owns, the text.
func docPage(t Thread, d Doc, text string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "---\ntype: %s\nthread: %s\ntitle: %q\n", d.Stage, t.ID, t.Title)
	if d.Stage == Receipt {
		fmt.Fprintf(&b, "outcome: %s\n", d.Outcome)
	}
	fmt.Fprintf(&b, "created: %s\n---\n\n%s\n", d.Created, docLead(t, d))
	if text != "" {
		b.WriteString("\n" + text + "\n")
	}
	return b.String()
}

// link is a markdown link from a page to another, both relative to the project folder,
// so it opens in Obsidian and in any other viewer.
func link(label, from, to string) string {
	rel, err := filepath.Rel(path.Dir(from), to)
	if err != nil {
		rel = to
	}
	return fmt.Sprintf("[%s](<%s>)", label, filepath.ToSlash(rel))
}

// calloutTitle keeps a title on the callout's one title line.
func calloutTitle(s string) string {
	return strings.NewReplacer("\n", " ", "[", "(", "]", ")").Replace(s)
}

// docLead is the callout at the top of a stage document: the stage's color and icon, the
// way to every other document of the thread, and the thread's id.
func docLead(t Thread, d Doc) string {
	kind, title := d.Stage, calloutTitle(t.Title)
	if d.Stage == Receipt {
		title += " · " + d.Outcome
		if d.Outcome == Killed {
			kind = Killed
		}
	}
	var trail []string
	for _, stage := range Stages {
		other := t.Doc(stage)
		switch {
		case stage == d.Stage:
			trail = append(trail, "**"+Label(stage)+"**")
		case other != nil:
			trail = append(trail, link(Label(stage), d.Path, other.Path))
		default:
			trail = append(trail, Label(stage))
		}
	}
	return fmt.Sprintf("> [!%s] %s\n> %s\n> `%s` · %s · filed %s", kind, title, strings.Join(trail, " → "), t.ID, link("Thread", d.Path, t.Path), d.Created)
}

// cardBody is everything a card shows under its frontmatter: the thread's state, a link
// to each document, and the documents themselves embedded in order.
func cardBody(t Thread) string {
	var b strings.Builder
	state := "**" + Label(t.Stage) + "**"
	if t.Closed() {
		state = "**" + Label(t.Outcome) + "**"
	}
	facts := []string{state, t.Priority + " priority"}
	if t.Phase != "" {
		facts = append(facts, "phase "+t.Phase)
	}
	facts = append(facts, "opened "+t.Created, "updated "+t.Updated)
	fmt.Fprintf(&b, "> [!thread] %s\n> %s\n", calloutTitle(t.Title), strings.Join(facts, " · "))
	if t.Blocked != "" {
		fmt.Fprintf(&b, "> **Blocked:** %s\n", t.Blocked)
	}
	b.WriteString(">\n")
	for _, stage := range Stages {
		if d := t.Doc(stage); d != nil {
			fmt.Fprintf(&b, "> - %s · %s\n", link(Label(stage), t.Path, d.Path), d.Created)
		} else {
			fmt.Fprintf(&b, "> - %s · none\n", Label(stage))
		}
	}
	fmt.Fprintf(&b, ">\n> `%s` · generated by claude-atlas; write in the documents, not here.\n", t.ID)
	for _, d := range t.Docs {
		fmt.Fprintf(&b, "\n![[%s]]\n", strings.TrimSuffix(d.Path, path.Ext(d.Path)))
	}
	return b.String()
}

// ownLead matches the callout code writes at the top of a document or a phase page; a
// callout of any other type is the user's.
var ownLead = regexp.MustCompile(`^> \[!(stub|spec|plan|receipt|killed|phase)\]`)

// replaceLead puts lead in the place of the callout that opens a page's body, or before
// the body when none opens it. Everything else stays as it is.
func replaceLead(content, lead string) string {
	front, body, ok, err := vault.SplitFrontmatter(content)
	if err != nil {
		return content
	}
	rest := strings.TrimLeft(body, "\r\n")
	if ownLead.MatchString(rest) {
		lines := strings.SplitAfter(rest, "\n")
		i := 0
		for i < len(lines) && strings.HasPrefix(lines[i], ">") {
			i++
		}
		rest = strings.TrimLeft(strings.Join(lines[i:], ""), "\r\n")
	}
	out := lead + "\n"
	if rest != "" {
		out += "\n" + rest
	}
	if !ok {
		return out
	}
	return "---\n" + front + "---\n\n" + out
}

// writeIfChanged writes a page only when its content differs, so a sync that changes
// nothing touches no file.
func writeIfChanged(file, content string) error {
	if have, err := os.ReadFile(file); err == nil && string(have) == content {
		return nil
	}
	return os.WriteFile(file, []byte(content), 0o644)
}

// uniquePath is dir/base, or dir/base (n).md when that is taken.
func uniquePath(p *project.Project, dir, base string) string {
	stem := strings.TrimSuffix(base, path.Ext(base))
	candidate := dir + "/" + base
	for n := 2; exists(p, candidate); n++ {
		candidate = fmt.Sprintf("%s/%s (%d).md", dir, stem, n)
	}
	return candidate
}

// Sync makes every generated page say what the documents say: each card's stage, outcome,
// body, and folder (open cards in threads/, closed ones in threads/archive/), the callout
// that opens each document, and the board. It never changes `updated`, and it is safe to
// run at any time.
func Sync(p *project.Project, now time.Time) (*Board, error) {
	if err := p.EnsureFolders(); err != nil {
		return nil, err
	}
	board, err := Load(p)
	if err != nil {
		return nil, err
	}
	for i := range board.Threads {
		t := &board.Threads[i]
		want := project.ThreadsDir
		if t.Closed() {
			want = project.ArchiveDir
		}
		if path.Dir(t.Path) == want {
			continue
		}
		dest := uniquePath(p, want, path.Base(t.Path))
		if err := os.Rename(p.Path(t.Path), p.Path(dest)); err != nil {
			return nil, err
		}
		t.Path = dest
	}
	for _, t := range board.Threads {
		data, err := os.ReadFile(p.Path(t.Path))
		if err != nil {
			return nil, err
		}
		content := setField(setField(string(data), "stage", t.Stage), "outcome", fmt.Sprintf("%q", t.Outcome))
		front, _, _, _ := vault.SplitFrontmatter(content)
		if err := writeIfChanged(p.Path(t.Path), "---\n"+front+"---\n\n"+cardBody(t)); err != nil {
			return nil, err
		}
		for _, d := range t.Docs {
			data, err := os.ReadFile(p.Path(d.Path))
			if err != nil {
				return nil, err
			}
			if err := writeIfChanged(p.Path(d.Path), replaceLead(string(data), docLead(t, d))); err != nil {
				return nil, err
			}
		}
	}
	return board, writeIfChanged(p.Path(project.ThreadsIndex), RenderIndex(board, now))
}

func phaseLead(title string) string { return "> [!phase] " + calloutTitle(title) }

// PhaseSkeleton renders a phase page.
func PhaseSkeleton(title, goal string, order int, now time.Time) string {
	date := now.Format("2006-01-02")
	goal = strings.TrimSpace(goal)
	if goal == "" {
		goal = "What this phase delivers, and how you will know it is done."
	}
	return fmt.Sprintf("---\ntype: phase\ntitle: %q\norder: %d\ncreated: %s\nupdated: %s\n---\n\n%s\n\n## Goal\n\n%s\n", title, order, date, date, phaseLead(title), goal)
}

// RenderIndex renders threads/threads.md: the open threads by stage, the furthest stage
// first, then the phases and the closed threads. Each group is a callout in its stage's
// color.
func RenderIndex(b *Board, now time.Time) string {
	var w strings.Builder
	w.WriteString("# Threads\n\nGenerated by claude-atlas from the cards and the documents; do not edit. Write in a thread's documents, and change its card with the thread tool.\n")
	from := project.ThreadsIndex
	if len(b.Open()) == 0 {
		w.WriteString("\nNo open threads. Open one with the thread-stub skill, `claude-atlas thread . new \"...\"`, or a note in `inbox/`.\n")
	}
	for i := len(Stages) - 2; i >= 0; i-- {
		stage := Stages[i]
		at := b.At(stage)
		if len(at) == 0 {
			continue
		}
		fmt.Fprintf(&w, "\n> [!%s] %s · %d\n> | Thread | %s | Priority | Phase | Updated | |\n> |:--|:--|:--|:--|:--|:--|\n", stage, Label(stage), len(at), Label(stage))
		for _, t := range at {
			var notes []string
			if t.Blocked != "" {
				notes = append(notes, "blocked: "+cell(t.Blocked))
			}
			if Stale(t, now) {
				notes = append(notes, "stale")
			}
			doc := "—"
			if d := t.Current(); d != nil {
				doc = link("open", from, d.Path)
			}
			fmt.Fprintf(&w, "> | %s | %s | %s | %s | %s | %s |\n", link(cell(t.Title), from, t.Path), doc, t.Priority, dash(cell(t.Phase)), dash(t.Updated), strings.Join(notes, " · "))
		}
	}
	if len(b.Phases) > 0 {
		w.WriteString("\n> [!phase] Phases\n> | Phase | Open | Closed | |\n> |:--|:--|:--|:--|\n")
		for _, ph := range b.Phases {
			closed := 0
			for _, t := range b.Threads {
				if t.Closed() && strings.EqualFold(t.Phase, ph.Title) {
					closed++
				}
			}
			note := ""
			if b.Finished(ph.Title) {
				note = "finished"
			}
			fmt.Fprintf(&w, "> | %s | %d | %d | %s |\n", link(cell(ph.Title), from, ph.Path), len(b.In(ph.Title)), closed, note)
		}
	}
	if closed := b.Closed(); len(closed) > 0 {
		fmt.Fprintf(&w, "\n> [!receipt] Closed · %d\n> | Thread | Receipt | Phase | Closed |\n> |:--|:--|:--|:--|\n", len(closed))
		for _, t := range closed {
			fmt.Fprintf(&w, "> | %s | %s | %s | %s |\n", link(cell(t.Title), from, t.Path), link(t.Outcome, from, t.Doc(Receipt).Path), dash(cell(t.Phase)), dash(t.Updated))
		}
	}
	if len(b.Problems) > 0 {
		w.WriteString("\n## Not readable\n\n")
		for _, pr := range b.Problems {
			fmt.Fprintf(&w, "- `%s`: %s\n", pr.Path, pr.Reason)
		}
	}
	return w.String()
}

// cell keeps text inside one table cell.
func cell(s string) string {
	return strings.NewReplacer("|", "\\|", "\n", " ", "[", "(", "]", ")").Replace(s)
}

func dash(s string) string {
	if s == "" {
		return "—"
	}
	return s
}
